"""Configuration validation tests (pydantic-settings)."""

import importlib

import pytest


def _fresh_config(monkeypatch, **env):
    for key, value in env.items():
        monkeypatch.setenv(key, value)
    import src.config as config
    config.get_settings.cache_clear()
    return config


def test_defaults(monkeypatch):
    config = _fresh_config(monkeypatch)
    settings = config.get_settings()
    assert settings.model == "openrouter/auto"
    assert settings.host == "127.0.0.1"
    assert settings.port == 8000
    assert settings.enable_code_execution is False
    assert settings.has_api_key is False


def test_allowed_origins_parsed_from_csv(monkeypatch):
    config = _fresh_config(
        monkeypatch,
        BLINK_ALLOWED_ORIGINS="http://a.com, http://b.com ,http://c.com",
    )
    settings = config.get_settings()
    assert settings.allowed_origins == ["http://a.com", "http://b.com", "http://c.com"]


def test_ws_token_autogenerated_when_blank(monkeypatch):
    config = _fresh_config(monkeypatch)
    settings = config.get_settings()
    # A per-process token should be generated so privileged actions stay gated.
    assert isinstance(settings.ws_auth_token, str)
    assert len(settings.ws_auth_token) >= 16


def test_ws_token_respects_explicit_value(monkeypatch):
    config = _fresh_config(monkeypatch, BLINK_WS_TOKEN="pinned-token")
    settings = config.get_settings()
    assert settings.ws_auth_token == "pinned-token"


def test_port_validation_rejects_out_of_range(monkeypatch):
    from pydantic import ValidationError
    with pytest.raises(ValidationError):
        _fresh_config(monkeypatch, BLINK_PORT="70000").get_settings()


def test_save_and_load_config_roundtrip(monkeypatch):
    config = _fresh_config(monkeypatch)
    assert config.load_config() is False  # no key yet
    config.save_config("sk-or-test-key", "openrouter/auto")
    assert config.load_config() is True
    assert config.get_settings().has_api_key is True


def test_api_key_is_stripped(monkeypatch):
    config = _fresh_config(monkeypatch, OPENROUTER_API_KEY="  sk-or-padded  ")
    assert config.get_settings().openrouter_api_key == "sk-or-padded"
